{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paperless-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  type: {{ .Values.services.redis.type }}
  ports:
    - port: {{ .Values.services.redis.port }}
      targetPort: {{ .Values.services.redis.targetPort }}
      protocol: TCP
      name: redis
  selector:
    {{- include "paperless-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cache
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "paperless-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      {{- include "paperless-stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cache
  template:
    metadata:
      labels:
        {{- include "paperless-stack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cache
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.services.redis.targetPort }}
              name: redis
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: redis-data
              mountPath: {{ .Values.redis.data.mountPath }}
          args:
            {{- if .Values.redis.auth.enabled }}
            - "--requirepass"
            - "{{ .Values.redis.auth.password }}"
            {{- end }}
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.redis.data.storageClass }}
        storageClassName: {{ .Values.redis.data.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.data.size }}
{{- end }}
